### ISSUE TITLE
Persistence des tamagos morts

### ISSUE THREAD

**Issue by Lauwed** [DevGirl-Team/tamagokill#11]
Grande question.

Question statistique, comment garde-t-on une trace, un historique des Tamago tués ?

![Frame 2](https://github.com/DevGirl-Team/tamagokill/assets/15716589/a551012f-db9d-491e-a739-43fb589b2284)

Il y a deux propositions : 
1. Création d'une nouvelle instance Tamago avec un `bool` qui indique si le Tamago est mort ou non. L'instance du Tamago mort n'est pas supprimée. (gauche)
![image](https://github.com/DevGirl-Team/tamagokill/assets/15716589/79d73057-019d-4cba-a686-22103e919de0)

2. On garde la même instance, on remet les stats à zéro, on modifie tout ce qu'il faut pour le nouveau Tamago, et une ligne dans un table `cimetary` sera créée pour le Tamago fraichement mort avec seulement les données nécessaires. (droite)
![image](https://github.com/DevGirl-Team/tamagokill/assets/15716589/ffb5d435-b88e-4eb7-ad99-a31b8e0b6d7e)

L'argument principal du 2ème point est de ne pas saturer la DB et une question de performance.

**OUBLIEZ PAS DE VOTER POUR VOTRE METHODE PREFEREE**

Réagissez avec l'emote 👀 pour le 1er scénario et 🚀 pour le 2ème scénario.

**Comment by circular17** [comment]
Théoriquement je ferais l'option 1, parce que c'est plusse comme la "forme normale" et cela permet de garder une historique avec les relations, "remonter dans le temps" si on veut.

D'ailleurs on pourrait mettre une date de mort plutôt qu'un booléen.

Dans la pratique, si on vise le mmorpg, que y a beaucoup beaucoup de lignes, c'est mieux la deuxième option, qui permet notamment de supprimer facilement l'historique si on veut "faire de la place".
