### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by Lauwed** [DevGirl-Team/tamagokill#16]
Everything is in the title 🤠

**Comment by guidu69** [comment]
Hello !
Je suppose que tu parles français étant belge :p
J'ai pas trouvé la section adéquate pour poster mon message donc je le fais ici :
J'ai trouvé ton repo github par hasard en explorant github et je trouve le concept hyper sympa.
Je propose d'ouvrir un serveur discord pr communiquer sur le projet et le dev !
J'en profiterai pour me présenter ;)
Bonne soirée,
Guillaume
EDIT : je l'ai ouvert le discord y'a plus qu'à rejoindre : https://discord.gg/BdZNQdGV

**Comment by Lauwed** [comment]
Hello !
Merci beaucoup pour ton message, c'est super cool que tu aies pu trouver ce projet et qu'il t'intéresse.

C'est vrai que j'avais complètement oublié d'indiquer un Discord sur le README, c'est chose faite ! Je travaille sur le projet avec ma communauté Twitch, j'ai une catégorie spéciale pour le projet dans mon serveur Discord, n'hésite pas à le rejoindre ici : [discord.gg/Njh6vWPH2h](discord.gg/Njh6vWPH2h0)

Désolé que tu aies du créer un serveur Discord 🫠 mais l'initiative est géniale !

Belle journée.
