### ISSUE TITLE
Ajout environnents dev et prod au Docker ?

### ISSUE THREAD

**Issue by Lauwed** [DevGirl-Team/tamagokill#2]
Ça serait cool de pas devoir rebuild le contianer à chaque modification dans les projets Web et API.

Des idées ?

**Comment by pbrissaud** [comment]
La version  2.22.0 de Docker compose apporte une fonctionnalité de [`watch`](https://docs.docker.com/compose/file-watch/) qui permet de synchroniser le système de fichier et de reload le conteneur après changement. Cela permet aussi de reconstruire sous certaines conditions (comme un ajout de package). 

Pour l'API il faut rajouter en plus un package `cargo watch` qui permet de faire du hot reloading. 

Cf. ma PR qui implémente cette solution #3
